### ISSUE TITLE
Memory error running CellAssign depending on size of marker gene set reference

### ISSUE THREAD

**Issue by sjspielman** [scverse/scvi-tools#2935]
I am trying to use CellAssign with GPU to varying success. I am finding that CellAssign is giving memory availability errors (`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.57 GiB. GPU 0 has a total capacity of 14.58 GiB of which 3.35 GiB is free` etc.....) based on the size of the marker gene reference file. The reference I have prepared for use is 2274 genes x ~70 cell types. I can only get CellAssign to run without a memory allocation error if I drop the number of genes to ~400. The size of the AnnData itself don't seem to cause this problem, but larger reference files do.

I am wondering if this is a known issue, or you have any recommendations for preparing marker gene reference sets that will not cause this sort of error? Thanks very much! The file whi

I am attaching here a version of the reference gene file that runs for me and one that does not - 

- [brain-reference-runs.tsv.txt](https://github.com/user-attachments/files/16587910/brain-reference-runs.tsv.txt)
- [brain-reference-fails.tsv.txt](https://github.com/user-attachments/files/16587947/brain-reference-fails.tsv.txt)

I can't directly attach the dataset I am running it with due to sharing restrictions, but the dataset is freely available for download here. It's the `SCPCL000001_processed_rna.h5ad` file associated with the download for sample `SCPCS000001`: https://scpca.alexslemonade.org/projects/SCPCP000001. Note that I have encountered the same memory error with other AnnData files, including those up to nearly 1 GB which again run with the smaller marker gene reference but not the full set I hope to use.
 
Here is the crux of the code I am using to run CellAssign:
```python
import anndata as adata
import pandas as pd
import scvi
from scvi.external import CellAssign

scvi.settings.seed = 2024

# read in marker gene reference - this one runs
ref_matrix = pd.read_csv(
    "brain-reference-runs.tsv", sep="\t", index_col="ensembl_gene_id"
)

# read in anndata
adata = adata.read_h5ad("SCPCL000001_processed_rna.h5ad")

# subset anndata to contain only genes in the reference file
shared_genes = list(set(ref_matrix.index) & set(annotated_adata.var_names))
subset_adata = adata[:, shared_genes].copy()
subset_adata.X = subset_adata.X.tocsr()

# add size factor to subset adata (calculated from full data)
lib_size = adata.X.sum(1)
subset_adata.obs["size_factor"] = lib_size / np.mean(lib_size)

# CellAssign inference
scvi.external.CellAssign.setup_anndata(subset_adata, size_factor_key="size_factor")
model = CellAssign(subset_adata, ref_matrix)
model.train(accelerator="gpu")
predictions = model.predict()
```

#### Versions:

> 1.1.5

I am running in a conda environment built from [environment.yml.txt](https://github.com/user-attachments/files/16587877/environment.yml.txt).

Thanks very much for any insights into what might be going on here!

**Comment by canergen** [comment]
Hi. It says 3.5GB is free on the GPU which is very little. Can you use an empty GPU? A free Colab GPU would be sufficient for your purpose. I assume we could optimize RAM use but this won’t be a priority in the coming months if it works fine on 16GB of VRAM.

**Comment by canergen** [comment]
I assume it happens during the predict function. If it still fails can you verify it. I don’t plan changing the model but changing inference would be straightforward (and we have two solutions to it).

**Comment by sjspielman** [comment]
Hello, wanted to share a quick update. I have been for now working locally to figure out when the GPU is filling up, running line-by-line in an interactive python session with `nvidia-smi -l i` running so I can monitor usage. 

The GPU indeed appears essentially free until I run the `.train()` line, at which point it starts ramping up and fills up. This is what I see up through and including the line `model = CellAssign(subset_adata, ref_matrix)`:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0              26W /  70W |    395MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

Then, when I issue `model.train(accelerator="gpu")`, I see the memory go up to `1407/15360MiB`, but then it immediately fails with:
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.57 GiB. GPU 0 has a total capacity of 14.58 GiB of which 3.36 GiB is free. Process 2242 has 247.95 MiB memory in use. Including non-PyTorch memory, this process has 10.98 GiB memory in use. Of the allocated memory 10.84 GiB is allocated by PyTorch, and 18.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

...in spite of what looks like a decent amount of available memory as seen in the `nvidia-smi` output - 

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0              26W /  70W |   1407MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2242      C   /usr/lib/x86_64-linux-gnu/dcv/dcvagent      247MiB |
|    0   N/A  N/A      7456      C   python3                                    1154MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by canergen** [comment]
Hi, can you pass a smaller batch_size like `model.train(accelerator="gpu", batch_size=32)`. You can then increase it to maximize usage of GPU RAM. The current default is 1024. However, it creates several tensors of n_cellsXn_genesXn_celltypes and this is apparently too large in your case.

**Comment by sjspielman** [comment]
> Hi, can you pass a smaller batch_size like model.train(accelerator="gpu", batch_size=32).

Thank you @canergen, this worked for me to get CellAssign running with my full marker genes set (and if not the most efficiently, at least more efficiently than CPU). Appreciate the help!

**Comment by canergen** [comment]
Great, 128 will likely still work but you can see your memory use (consumption will be roughly linear with the batch side).

**Comment by sjspielman** [comment]
> Great, 128 will likely still work but you can see your memory use (consumption will be roughly linear with the batch side).

💯 , I was able to get up to 128, but not >=256
