### ISSUE TITLE
gimVI - multi-GPU support?

### ISSUE THREAD

**Issue by jachou1** [scverse/scvi-tools#3057]
I'm currently running gimVI on 14K genes to impute spatial expression from scRNA-seq data. My model trains, but then I can't get the imputed expression using model.get_imputed_values(). My 1 GPU has ran out of memory.

```python
imputed_spatial_rates = model.get_imputed_values(normalized= False)[1]
```

```pytb
OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 44.53 GiB of which 448.00 KiB is free. Including non-PyTorch memory, this process has 44.52 GiB memory in use. Of the allocated memory 36.12 GiB is allocated by PyTorch, and 7.91 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)```

#### Versions:

<!-- Output of scvi.__version__ -->

> VERSION
1.2.0


<!-- Relevant screenshots -->

Question: Can I run on multi-GPUs to get the learned expression for GIMVI to overcome this out-of-memory problem? 

Thank you.!

[Image](https://github.com/user-attachments/assets/e6ae4441-56b2-4530-956f-d9710f60bb3b)

**Comment by canergen** [comment]
Multi-GPU might help here, but looking at the numbers, it’s more likely a coding error. We should fetch mini-batches to CPU in https://github.com/scverse/scvi-tools/blob/bcd7e6722d43dfdec4e9b63d5f650a638202c124/src/scvi/external/gimvi/_model.py#L366 instead of first collecting all and then transferring to CPU. @ori-kron-wis Can you create a PR?

**Comment by canergen** [comment]
To explain the error a bit more, GIMVI was taking up the 44GB:
`this process has 44.52 GiB memory in use. Of the allocated memory 36.12 GiB is allocated by PyTorch`
The simple model shouldn’t use up that much memory. If it still fails in the branch. Can you share memory usage after model training, dataset size and perform inference using a subset of the data using a subset AnnData object?

**Comment by jachou1** [comment]
Hi, apologies for delay in response. It was Thanksgiving in the states, and I hadn't expected such a quick response and turnaround. Thanks so much for fixing it. But I'm having difficulty getting your latest code change. I see you've already merged the change to the main branch of this repo. I tried installing using pip install git+https://github.com/scverse/scvi-tools.git@main, but I get the following error. ![Image](https://github.com/user-attachments/assets/05a1fe02-877d-4490-8a94-0a3fb9aaf07a)
What's the best way for me to get this changed code? Thank you!

**Comment by jachou1** [comment]
@ori-kron-wis Yes, it still fails. It seems the model still takes up too much memory. ![Image](https://github.com/user-attachments/assets/941bbcfb-a43d-41fd-acbc-4b8d2ed22ba0)

So the model finished training for this large dataset. Spatial_ad: 830K cells x 427 genes, and single_cell_ad: 300K x 14K genes. I'm trying to impute the spatial data from the single-cell reference dataset. Is this just too large of a dataset for the model to handle?

I then tried to subset the data to just 1 tissue in the spatial_ad. So it's 48K cells x 427 genes (spatial_ad) and single_cell_ad: 300K cells x 14K, but I run into an error with NaNs in the tensor. ![Image](https://github.com/user-attachments/assets/87d1ac1e-75b7-4f55-8403-c5b1a4541ed1)

I saw this error has popped up previously. 

Is the issue with CUDA out of memory expected with such a large dataset? And how best to train the GIMVI model on my dataset? Thank you.

**Comment by canergen** [comment]
The screenshot is without the fix. It’s still cpu transfer after concatenating. Can you try to install from main again?
I thought the NaN error was fixed (adversarial classifier with a single batch) and have to check why it’s still popping up.

**Comment by jachou1** [comment]
Tried installing from main, and it is resolved in terms of CUDA out of memory error. Thank you. Not sure the source of the NaN error. It happens sporadically during training. Could you comment on whether using 200 epochs is necessary to reach convergence for gimVI? Or is it dependent on the dataset at-hand?
